# Travis.yml for the build bot for noteblocks
language: ruby
# Using .ruby-version so no need for an rvm key

# Install is handled by bundler in the travis ruby buildpack
cache: bundler

# Need to initialize a test postgres db
services:
  - postgresql

# Prepare test env
before_script:
  - psql -c "CREATE USER nb_user WITH PASSWORD 'pass';" -U postgres
  - psql -c "ALTER USER nb_user CREATEDB;" -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rails db:create db:schema:load

# run tests
script:
  - bundle exec rspec -fd
